services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: campuscontrol-img
    container_name: campus-app
    restart: unless-stopped
    # Cambiamos /var/www a /var/www/html para que coincida con tu Dockerfile
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=jfuser
      - DB_PASSWORD=user_password
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: jfuser
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
